version: '3'

services:
  service-agent:
    build: ../..
    image: 2060-service-agent
    container_name: phonenumbervs-service-agent
    restart: always
    networks:
      - phonenumbervs
    ports:
      - 3100:3000
      - 3101:3001
    environment:
      - AGENT_PUBLIC_DID=did:web:10.82.14.12%3A3101
      - AGENT_ENDPOINT=ws://10.82.14.12:3101
      - ANONCREDS_BASE_URL=http://10.82.14.12:3101
      - AGENT_NAME=Phone Number Verification Service Agent
      - USE_CORS=true
      - EVENTS_BASE_URL=http://phonenumbervs-backend:5000
    volumes:
      - ./afj:/root/.afj

  phonenumbervs-backend:
    build: .
    image: 2060-service-agent-phonenumbervs
    container_name: phonenumbervs-backend
    restart: always
    networks:
      - phonenumbervs
    ports:
      - 5100:5000
    environment:
      - PORT=5000
      - SERVICE_AGENT_ADMIN_BASE_URL=http://phonenumbervs-service-agent:3000
networks:
  phonenumbervs:
