version: '3'

services:
  service-agent:
    build: ../..
    image: 2060-service-agent
    container_name: chatbot-service-agent
    restart: always
    networks:
      - chatbot
    ports:
      - 2800:3000
      - 2801:3001
    environment:
      - AGENT_PUBLIC_DID=did:web:p2801.ovpndev.2060.io
      - AGENT_ENDPOINT=wss://p2801.ovpndev.2060.io
      - AGENT_INVITATION_IMAGE_URL=http://172.26.26.3:2903/avatar.png
      - AGENT_LABEL=Unic id (dev)
      - ANONCREDS_SERVICE_BASE_URL=https://p2801.ovpndev.2060.io
      - USE_CORS=true
      - EVENTS_BASE_URL=http://172.26.26.3:2903
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=gaia
      - POSTGRES_PASSWORD=2060demo
      - AGENT_WALLET_KEY_DERIVATION_METHOD=ARGON2I_INT
      - AGENT_INVITATION_BASE_URL=https://hologram.zone/
      - REDIS_HOST=redis
  #   volumes:
  #     - ./afj:/root/.afj
  # chatbot-backend:
  #   build: .
  #   image: 2060-service-agent-chatbot
  #   container_name: chatbot-backend
  #   restart: always
  #   networks:
  #     - chatbot
  #   ports:
  #     - 2802:5000
  #   environment:
  #     - PORT=5000
  #     - SERVICE_AGENT_ADMIN_BASE_URL=https://p2800.ovpndev.2060.io/v1
  #     - PUBLIC_BASE_URL=https://p2802.ovpndev.2060.io
  #     - WEBRTC_SERVER_BASE_URL=https://v3demo.mediasoup.org
  #     - PNVS_SERVICE_AGENT_ADMIN_BASE_URL=http://10.82.14.12:3100

  redis:
    image: redis:alpine
    restart: always
    networks:
      - chatbot
    ports:
      - 6379:6379
    command: redis-server --maxmemory 64mb --maxmemory-policy allkeys-lru

  postgres:
    image: postgres:15.2
    restart: always
    networks:
      - chatbot
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=2060demo
      - POSTGRES_USER=gaia
  datastore:
    image: io2060/2060-datastore:main
    user: root
    ports:
       - "2804:2604"
    restart: unless-stopped
    environment:
    - DEBUG=1
    - QUARKUS_HTTP_PORT=2604
    - IO_TWENTYSIXTY_DATASTORE_TMP_DIR=/tmp/data/tmp
    - IO_TWENTYSIXTY_DATASTORE_TMP_LIFETIMEDAYS=5
    - IO_TWENTYSIXTY_DATASTORE_REPO_LIFETIMEDAYS=43800
    - IO_TWENTYSIXTY_DATASTORE_REPO_FS_DIR=/tmp/data/repo
    - IO_TWENTYSIXTY_DATASTORE_MEDIA_MAXCHUNKS=128
    volumes:
       - /tmp/data:/tmp/data
    networks:
       - "chatbot"
networks:
  chatbot:
