name: Continuous Integration

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, labeled]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout service-agent
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup node v20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Install dependencies
        run: |
          yarn install --immutable

      - name: Build
        run: |
          yarn build

      - name: Check Format
        run: |
          yarn check-format

      - name: Check Types
        run: |
          yarn check-types

      - name: Publish NPM packages
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          RELEASE_VERSION: 0.0.0-beta.${{ github.run_number }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ~/.npmrc
          yarn config set npmAuthToken ${NPM_AUTH_TOKEN}
          yarn workspaces foreach --topological version $RELEASE_VERSION
          yarn up @2060.io/service-agent-model@$RELEASE_VERSION
          yarn up @2060.io/service-agent-client@$RELEASE_VERSION
          yarn workspaces foreach --topological --no-private --exclude @2060.io/service-agent-main npm publish
